spring.application.name=queuemanagement
spring.datasource.url=jdbc:postgresql://localhost:5432/queue_management
spring.datasource.username=postgres
spring.datasource.password=smart
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}